apiVersion: apps/v_f # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: react-deployment 
spec: 
  selector: 
    matchLabels: 
      app: react 
  replicas: 2 # tells deployment to run 2 pods matching the template 
  template: 
    metadata: 
      labels: 
        app: react 
    spec: 
      containers: 
      - name: react 
        image: helloezmeral/covid19:v_f 
        ports: 
        - containerPort: 80 
---
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: react-service 
spec: 
  selector: 
    app: react 
  ports: 
  - protocol: TCP 
    port: 80
    targetPort: 80 
    nodePort: 32000 
  type: LoadBalancer 